# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dinesoo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import image, sys


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(469, 595)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 481, 601))
        self.frame.setStyleSheet("\n"
"background-color: rgb(249, 248, 229);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(90, 20, 301, 61))
        self.label.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"\n"
"color: rgb(88, 75, 53);")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 260, 171, 131))
        self.label_3.setStyleSheet("image: url(:/tugas2/pict/cappuccino.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(0, 130, 231, 111))
        self.label_4.setStyleSheet("image: url(:/tugas2/pict/espresso.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(40, 410, 141, 131))
        self.label_5.setStyleSheet("image: url(:/tugas2/pict/flat white.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(190, 120, 71, 21))
        self.label_6.setStyleSheet("font: 10pt \"Century Gothic\";\n"
"color: rgb(88, 75, 53);\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(190, 140, 81, 21))
        self.label_7.setStyleSheet("font: 11pt \"Century Gothic\";\n"
"color: rgb(88, 75, 53);\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(190, 170, 71, 21))
        self.label_8.setStyleSheet("font: 9pt \"Century Gothic\";\n"
"color: rgb(88, 75, 53);\n"
"")
        self.label_8.setObjectName("label_8")
        self.Quantity = QtWidgets.QSpinBox(self.frame)
        self.Quantity.setGeometry(QtCore.QRect(190, 190, 42, 22))
        self.Quantity.setStyleSheet("color: rgb(88, 75, 53);\n"
"font: 8pt \"Century Gothic\";")
        self.Quantity.setObjectName("Quantity")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(190, 280, 101, 21))
        self.label_9.setStyleSheet("font: 9pt \"Century Gothic\";\n"
"color: rgb(88, 75, 53);\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(190, 300, 81, 21))
        self.label_10.setStyleSheet("font: 11pt \"Century Gothic\";\n"
"color: rgb(88, 75, 53);\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(190, 330, 71, 21))
        self.label_11.setStyleSheet("font: 9pt \"Century Gothic\";\n"
"color: rgb(88, 75, 53);\n"
"")
        self.label_11.setObjectName("label_11")
        self.Quantity_2 = QtWidgets.QSpinBox(self.frame)
        self.Quantity_2.setGeometry(QtCore.QRect(190, 350, 42, 22))
        self.Quantity_2.setStyleSheet("color: rgb(88, 75, 53);\n"
"font: 8pt \"Century Gothic\";")
        self.Quantity_2.setObjectName("Quantity_2")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(190, 430, 101, 21))
        self.label_12.setStyleSheet("font: 9pt \"Century Gothic\";\n"
"color: rgb(88, 75, 53);\n"
"")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(190, 450, 81, 21))
        self.label_13.setStyleSheet("font: 11pt \"Century Gothic\";\n"
"color: rgb(88, 75, 53);\n"
"")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(190, 480, 71, 21))
        self.label_14.setStyleSheet("font: 9pt \"Century Gothic\";\n"
"color: rgb(88, 75, 53);\n"
"")
        self.label_14.setObjectName("label_14")
        self.Quantity_3 = QtWidgets.QSpinBox(self.frame)
        self.Quantity_3.setGeometry(QtCore.QRect(190, 500, 42, 22))
        self.Quantity_3.setStyleSheet("color: rgb(88, 75, 53);\n"
"font: 8pt \"Century Gothic\";")
        self.Quantity_3.setObjectName("Quantity_3")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(310, 140, 111, 22))
        self.comboBox.setStyleSheet("color: rgb(88, 75, 53);\n"
"font: 8pt \"Century Gothic\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setItemText(5, "")
        self.comboBox.addItem("")
        self.comboBox.setItemText(6, "")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(310, 120, 101, 20))
        self.label_15.setStyleSheet("font: 9pt \"Century Gothic\";\n"
"color: rgb(88, 75, 53);\n"
"")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(310, 170, 101, 20))
        self.label_16.setStyleSheet("font: 9pt \"Century Gothic\";\n"
"color: rgb(88, 75, 53);\n"
"")
        self.label_16.setObjectName("label_16")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(310, 190, 111, 22))
        self.comboBox_2.setStyleSheet("color: rgb(88, 75, 53);\n"
"font: 8pt \"Century Gothic\";")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(310, 280, 101, 20))
        self.label_17.setStyleSheet("font: 9pt \"Century Gothic\";\n"
"color: rgb(88, 75, 53);\n"
"")
        self.label_17.setObjectName("label_17")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame)
        self.comboBox_3.setGeometry(QtCore.QRect(310, 300, 111, 22))
        self.comboBox_3.setStyleSheet("color: rgb(88, 75, 53);\n"
"font: 8pt \"Century Gothic\";")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(5, "")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(6, "")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(310, 330, 101, 20))
        self.label_18.setStyleSheet("font: 9pt \"Century Gothic\";\n"
"color: rgb(88, 75, 53);\n"
"")
        self.label_18.setObjectName("label_18")
        self.comboBox_4 = QtWidgets.QComboBox(self.frame)
        self.comboBox_4.setGeometry(QtCore.QRect(310, 350, 111, 22))
        self.comboBox_4.setStyleSheet("color: rgb(88, 75, 53);\n"
"font: 8pt \"Century Gothic\";")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(310, 420, 101, 20))
        self.label_19.setStyleSheet("font: 9pt \"Century Gothic\";\n"
"color: rgb(88, 75, 53);\n"
"")
        self.label_19.setObjectName("label_19")
        self.comboBox_5 = QtWidgets.QComboBox(self.frame)
        self.comboBox_5.setGeometry(QtCore.QRect(310, 440, 111, 22))
        self.comboBox_5.setStyleSheet("color: rgb(88, 75, 53);\n"
"font: 8pt \"Century Gothic\";")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.setItemText(5, "")
        self.comboBox_5.addItem("")
        self.comboBox_5.setItemText(6, "")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(310, 480, 101, 20))
        self.label_20.setStyleSheet("font: 9pt \"Century Gothic\";\n"
"color: rgb(88, 75, 53);\n"
"")
        self.label_20.setObjectName("label_20")
        self.comboBox_6 = QtWidgets.QComboBox(self.frame)
        self.comboBox_6.setGeometry(QtCore.QRect(310, 500, 111, 22))
        self.comboBox_6.setStyleSheet("color: rgb(88, 75, 53);\n"
"font: 8pt \"Century Gothic\";")
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 550, 91, 31))
        self.pushButton_3.setStyleSheet("border-radius:10px;\n"
"background-color:rgb(88, 75, 53);\n"
"color:rgb(221, 222, 169);\n"
"font-size:16px;\n"
"font-weight:200px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_55 = QtWidgets.QLabel(self.frame)
        self.label_55.setGeometry(QtCore.QRect(160, 70, 151, 16))
        self.label_55.setStyleSheet("font: 8pt \"Century Gothic\";\n"
"color: rgb(88, 75, 53);\n"
"")
        self.label_55.setObjectName("label_55")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(380, 0, 91, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_56 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_56.setStyleSheet("image: url(:/tugas2/pict/KM.png);\n"
"")
        self.label_56.setText("")
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_5.addWidget(self.label_56)
        self.label_57 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_57.setStyleSheet("image: url(:/tugas2/pict/unmul.png);")
        self.label_57.setText("")
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_5.addWidget(self.label_57)
        self.label_58 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_58.setStyleSheet("image: url(:/tugas2/pict/ICON.png);")
        self.label_58.setText("")
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_5.addWidget(self.label_58)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.Quantity_2, self.Quantity)
        Form.setTabOrder(self.Quantity, self.comboBox)
        Form.setTabOrder(self.comboBox, self.comboBox_2)
        Form.setTabOrder(self.comboBox_2, self.comboBox_4)
        Form.setTabOrder(self.comboBox_4, self.comboBox_3)
        Form.setTabOrder(self.comboBox_3, self.comboBox_5)
        Form.setTabOrder(self.comboBox_5, self.comboBox_6)
        Form.setTabOrder(self.comboBox_6, self.pushButton_3)
        Form.setTabOrder(self.pushButton_3, self.Quantity_3)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Dinesoo\'s Coffe Order "))
        self.label_6.setText(_translate("Form", "Esspresso"))
        self.label_7.setText(_translate("Form", "Rp. 20.000,-"))
        self.label_8.setText(_translate("Form", "Quantity"))
        self.label_9.setText(_translate("Form", "Cappuccino"))
        self.label_10.setText(_translate("Form", "Rp. 25.000,-"))
        self.label_11.setText(_translate("Form", "Quantity"))
        self.label_12.setText(_translate("Form", "Flat White"))
        self.label_13.setText(_translate("Form", "Rp. 28.000,-"))
        self.label_14.setText(_translate("Form", "Quantity"))
        self.comboBox.setItemText(0, _translate("Form", "Select"))
        self.comboBox.setItemText(1, _translate("Form", "Less Sugar"))
        self.comboBox.setItemText(2, _translate("Form", "More Sugar"))
        self.comboBox.setItemText(3, _translate("Form", "Less Ice"))
        self.comboBox.setItemText(4, _translate("Form", "No Ice"))
        self.label_15.setText(_translate("Form", "Add-ons:"))
        self.label_16.setText(_translate("Form", "Size:"))
        self.comboBox_2.setItemText(0, _translate("Form", "Select"))
        self.comboBox_2.setItemText(1, _translate("Form", "Demi"))
        self.comboBox_2.setItemText(2, _translate("Form", "Short"))
        self.comboBox_2.setItemText(3, _translate("Form", "Tall"))
        self.comboBox_2.setItemText(4, _translate("Form", "Grande"))
        self.comboBox_2.setItemText(5, _translate("Form", "Venti"))
        self.comboBox_2.setItemText(6, _translate("Form", "Trenta"))
        self.label_17.setText(_translate("Form", "Add-ons:"))
        self.comboBox_3.setItemText(0, _translate("Form", "Select"))
        self.comboBox_3.setItemText(1, _translate("Form", "Less Sugar"))
        self.comboBox_3.setItemText(2, _translate("Form", "More Sugar"))
        self.comboBox_3.setItemText(3, _translate("Form", "Less Ice"))
        self.comboBox_3.setItemText(4, _translate("Form", "No Ice"))
        self.label_18.setText(_translate("Form", "Size:"))
        self.comboBox_4.setItemText(0, _translate("Form", "Select"))
        self.comboBox_4.setItemText(1, _translate("Form", "Demi"))
        self.comboBox_4.setItemText(2, _translate("Form", "Short"))
        self.comboBox_4.setItemText(3, _translate("Form", "Tall"))
        self.comboBox_4.setItemText(4, _translate("Form", "Grande"))
        self.comboBox_4.setItemText(5, _translate("Form", "Venti"))
        self.comboBox_4.setItemText(6, _translate("Form", "Trenta"))
        self.label_19.setText(_translate("Form", "Add-ons:"))
        self.comboBox_5.setItemText(0, _translate("Form", "Select"))
        self.comboBox_5.setItemText(1, _translate("Form", "Less Sugar"))
        self.comboBox_5.setItemText(2, _translate("Form", "More Sugar"))
        self.comboBox_5.setItemText(3, _translate("Form", "Less Ice"))
        self.comboBox_5.setItemText(4, _translate("Form", "No Ice"))
        self.label_20.setText(_translate("Form", "Size:"))
        self.comboBox_6.setItemText(0, _translate("Form", "Select"))
        self.comboBox_6.setItemText(1, _translate("Form", "Demi"))
        self.comboBox_6.setItemText(2, _translate("Form", "Short"))
        self.comboBox_6.setItemText(3, _translate("Form", "Tall"))
        self.comboBox_6.setItemText(4, _translate("Form", "Grande"))
        self.comboBox_6.setItemText(5, _translate("Form", "Venti"))
        self.comboBox_6.setItemText(6, _translate("Form", "Trenta"))
        self.pushButton_3.setText(_translate("Form", "Order"))
        self.label_55.setText(_translate("Form", "by Nadilla Putri Mulyadi"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())